language: php
sudo: false

cache:
    directories:
    - $HOME/.composer/cache


branches:
    only:
    - master
    - /^\d+\.\d+$/

matrix:
    fast_finish: true

    include:
        - php: 7.2
          env:
            - COMPOSER_FLAGS="--prefer-stable --prefer-lowest"

        - php: '7.2'

        - php: '7.3'
          env:
            - PHPSTAN=true

        - php: '7.4'

        - php: '8.0'

        - php: 'nightly'

    allow_failures:
        - php: nightly

install:
    # To be removed when this issue will be resolved: https://github.com/composer/composer/issues/5355
    - if [[ "$COMPOSER_FLAGS" == *"--prefer-lowest"* ]]; then composer update --prefer-dist --no-interaction --prefer-stable --quiet; fi
    - composer update ${COMPOSER_FLAGS} --prefer-dist --no-interaction

script:
    - composer validate --strict --no-check-lock
    - if [[ "$PHPSTAN" = true ]]; then composer phpstan-all; fi
    - composer phpunit
